### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/dbm-rawdata-runscript#2]
Possible bug when adding words?

`SyntaxError: Invalid regular expression: /\bsu)ck\b/: Unmatched ')'`

```
(node:13145) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/managers/GuildMemberManager.js:314:16
    at Timeout._onTimeout (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:13145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 220)
(node:13145) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\bsu)ck\b/: Unmatched ')'
    at new RegExp (<anonymous>)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:107:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 221)
```

**Comment by DanTheComputerMan** [comment]
I believe that issue is fixed.
